/* Generated By:JJTree: Do not edit this line. ASTArrayDimsAndInits.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTArrayDimsAndInits extends SimpleNode {
  public ASTArrayDimsAndInits(int id) {
    super(id);
  }

  public ASTArrayDimsAndInits(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e6c8f892fa04076f29e1f7b5b60d0501 (do not edit this line) */
