/* Generated By:JJTree: Do not edit this line. ASTAnnotationTypeMemberDeclaration.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTAnnotationTypeMemberDeclaration extends SimpleNode {
  public ASTAnnotationTypeMemberDeclaration(int id) {
    super(id);
  }

  public ASTAnnotationTypeMemberDeclaration(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=826b096bbae737b86da2c343cbddae70 (do not edit this line) */
