/* Generated By:JJTree: Do not edit this line. ASTBlockStatement.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTBlockStatement extends SimpleNode {
  public ASTBlockStatement(int id) {
    super(id);
  }

  public ASTBlockStatement(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d4a2d1f385eb0fe8402e7c1e7d8e62e5 (do not edit this line) */
