/* Generated By:JJTree: Do not edit this line. ASTClassOrInterfaceDeclaration.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTClassOrInterfaceDeclaration extends SimpleNode {
  private String image;
  public ASTClassOrInterfaceDeclaration(int id) {
    super(id);
  }

  public ASTClassOrInterfaceDeclaration(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }

  public void setImage(String image) {
    this.image = image;
  }

  public String getImage() {
    return image;
  }
}
/* JavaCC - OriginalChecksum=ba1c8fff0d4ee42f5cb27c5fc87deaa9 (do not edit this line) */
