/* Generated By:JJTree: Do not edit this line. ASTConstructorDeclaration.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTConstructorDeclaration extends SimpleNode {
  public ASTConstructorDeclaration(int id) {
    super(id);
  }

  public ASTConstructorDeclaration(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b7902e9da13fd226732c231971f7884c (do not edit this line) */
