/* Generated By:JJTree: Do not edit this line. ASTEnumConstant.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTEnumConstant extends SimpleNode {
  public ASTEnumConstant(int id) {
    super(id);
  }

  public ASTEnumConstant(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=334763ca90ff8c43c842d9719c4930c4 (do not edit this line) */
