/* Generated By:JJTree: Do not edit this line. ASTForUpdate.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTForUpdate extends SimpleNode {
  public ASTForUpdate(int id) {
    super(id);
  }

  public ASTForUpdate(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=749e3df25d5061c69ac4c362bc7c3e03 (do not edit this line) */
