/* Generated By:JJTree: Do not edit this line. ASTImplementsList.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTImplementsList extends SimpleNode {
  public ASTImplementsList(int id) {
    super(id);
  }

  public ASTImplementsList(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5e5a161d28a3a86e6b37e21e37e57d3b (do not edit this line) */
