/* Generated By:JJTree: Do not edit this line. ASTMemberValuePair.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTMemberValuePair extends SimpleNode {
  public ASTMemberValuePair(int id) {
    super(id);
  }

  public ASTMemberValuePair(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=d01568e24cf675ab04e85cf8fed01120 (do not edit this line) */
