/* Generated By:JJTree: Do not edit this line. ASTMemberValuePairs.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTMemberValuePairs extends SimpleNode {
  public ASTMemberValuePairs(int id) {
    super(id);
  }

  public ASTMemberValuePairs(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=078c910956d45838d4493350370778b5 (do not edit this line) */
