/* Generated By:JJTree: Do not edit this line. ASTMethodDeclarator.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTMethodDeclarator extends SimpleNode {
  private String image;
  public ASTMethodDeclarator(int id) {
    super(id);
  }

  public ASTMethodDeclarator(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }


  public void setImage(String image) {
    this.image = image;
  }

  public String getImage() {
    return image;
  }
}
/* JavaCC - OriginalChecksum=d5b2b9c659ebc83487b43895624af870 (do not edit this line) */
