/* Generated By:JJTree: Do not edit this line. ASTMarkerAnnotation.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTMarkerAnnotation extends SimpleNode {
  public ASTMarkerAnnotation(int id) {
    super(id);
  }

  public ASTMarkerAnnotation(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4812947746c8ed5c2bbd80f5d9934f43 (do not edit this line) */
