/* Generated By:JJTree: Do not edit this line. ASTRSIGNEDSHIFT.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTRSIGNEDSHIFT extends SimpleNode {
  public ASTRSIGNEDSHIFT(int id) {
    super(id);
  }

  public ASTRSIGNEDSHIFT(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a7fcc23771844b3ee40bb266efaf11f5 (do not edit this line) */
