/* Generated By:JJTree: Do not edit this line. ASTRUNSIGNEDSHIFT.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTRUNSIGNEDSHIFT extends SimpleNode {
  public ASTRUNSIGNEDSHIFT(int id) {
    super(id);
  }

  public ASTRUNSIGNEDSHIFT(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=71c18fa3bbd46ccc8bf00a2ed7a2ecc7 (do not edit this line) */
