/* Generated By:JJTree: Do not edit this line. ASTReferenceType.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTReferenceType extends SimpleNode {
  public ASTReferenceType(int id) {
    super(id);
  }

  public ASTReferenceType(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fed726a9f8383a3087745b749d0b7ec8 (do not edit this line) */
