/* Generated By:JJTree: Do not edit this line. ASTTypeDeclaration.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTTypeDeclaration extends SimpleNode {
  public ASTTypeDeclaration(int id) {
    super(id);
  }

  public ASTTypeDeclaration(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=20abba79ada56d56f8ee0bb250d0a7ef (do not edit this line) */
