/* Generated By:JJTree: Do not edit this line. ASTTypeArguments.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTTypeArguments extends SimpleNode {
  public ASTTypeArguments(int id) {
    super(id);
  }

  public ASTTypeArguments(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=477c54cd9b6e939bc8d3dd7574b1681d (do not edit this line) */
