/* Generated By:JJTree: Do not edit this line. ASTVariableDeclarator.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTVariableDeclarator extends SimpleNode {
  public ASTVariableDeclarator(int id) {
    super(id);
  }

  public ASTVariableDeclarator(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c9055315faa29e64e704ccc0602931d8 (do not edit this line) */
