/* Generated By:JJTree: Do not edit this line. ASTVariableDeclaratorId.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTVariableDeclaratorId extends SimpleNode {

  public String getImage() {
    return image;
  }

  private String image;
  public ASTVariableDeclaratorId(int id) {
    super(id);
  }

  public ASTVariableDeclaratorId(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }

    public void setImage(String image) {
        this.image = image;
    }
}
/* JavaCC - OriginalChecksum=fe20a5439bdec6ebd9a007820d1ab66a (do not edit this line) */
