/* Generated By:JJTree: Do not edit this line. ASTWildcardBounds.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTWildcardBounds extends SimpleNode {
  public ASTWildcardBounds(int id) {
    super(id);
  }

  public ASTWildcardBounds(JavaParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParserVisitor visitor, Object data) throws Exception {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=87d16ede5bd33905f52fac501451fdf0 (do not edit this line) */
